apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ulm-stack
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/mikenholt/argocd-helm-test.git
      revision: HEAD
      directories:
      - path: "apps-ulm/*"
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      destination:
        namespace: '{{path[0]}}'
        server: 'https://kubernetes.default.svc'
      source:
        repoURL: https://github.com/mikenholt/argocd-helm-test.git
        targetRevision: HEAD
        path: '{{path}}'
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
