apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: template
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/mikenholt/argocd-helm-test.git
      revision: HEAD
      files:
      - path: "config.yaml"
  template:
    metadata:
      name: {{path.basename}}
    spec:
      destination:
        namespace: '{{app_namespace}}'
        server: '{{server_address}}'
      source:
        repoURL: https://github.com/mikenholt/argocd-helm-test.git
        targetRevision: HEAD
        # path: '{{path}}'
        path: "apps-ulm/loki"
        helm:
          values: | 
            {{app_values}}
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
