server_address: https://kubernetes.default.svc

# Declare namespace for all apps
app_namespace: ulm

# Example global values
global_values: |
  test: true

# Example values specific to app
loki_values: |
  image:
    repository: hello-world
    tag: 1.0.0
